#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := esp_aws_iot_ble_scan

EXTRA_COMPONENT_DIRS := $(realpath ../esp-aws-iot)

include $(IDF_PATH)/make/project.mk

